<?php
class statistik extends CI_Model {
	public function stat1()
	{
		$q1 = $this->db->query("SELECT DISTINCT 
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 0) AS j0,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 1) AS j1,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 2) AS j2,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 3) AS j3,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 4) AS j4,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 5) AS j5,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 6) AS j6,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 7) AS j7,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 8) AS j8,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 9) AS j9,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 10) AS j10,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 11) AS j11,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 12) AS j12,		
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 13) AS j13,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 14) AS j14,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 15) AS j15,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 16) AS j16,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 17) AS j17,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 18) AS j18,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 19) AS j19,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 20) AS j20,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 21) AS j21,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 22) AS j22,
		(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 23) AS j23
		FROM COBA");
		return $q1->result();
	}
	public function stat2()
	{
		$q2 = $this->db->query("SELECT DISTINCT
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 0 AND EXTRACT(HOUR FROM jammasuk) <=0) AS ja0,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 1 AND EXTRACT(HOUR FROM jammasuk) <=1) AS ja1,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 2 AND EXTRACT(HOUR FROM jammasuk) <=2) AS ja2,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 3 AND EXTRACT(HOUR FROM jammasuk) <=3) AS ja3,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 4 AND EXTRACT(HOUR FROM jammasuk) <=4) AS ja4,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 5 AND EXTRACT(HOUR FROM jammasuk) <=5) AS ja5,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 6 AND EXTRACT(HOUR FROM jammasuk) <=6) AS ja6,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 7 AND EXTRACT(HOUR FROM jammasuk) <=7) AS ja7,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 8 AND EXTRACT(HOUR FROM jammasuk) <=8) AS ja8,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 9 AND EXTRACT(HOUR FROM jammasuk) <=9) AS ja9,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 10 AND EXTRACT(HOUR FROM jammasuk) <=10) AS ja10,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 11 AND EXTRACT(HOUR FROM jammasuk) <=11) AS ja11,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 12 AND EXTRACT(HOUR FROM jammasuk) <=12) AS ja12,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 13 AND EXTRACT(HOUR FROM jammasuk) <=13) AS ja13,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 14 AND EXTRACT(HOUR FROM jammasuk) <=14) AS ja14,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 15 AND EXTRACT(HOUR FROM jammasuk) <=15) AS ja15,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 16 AND EXTRACT(HOUR FROM jammasuk) <=16) AS ja16,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 17 AND EXTRACT(HOUR FROM jammasuk) <=17) AS ja17,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 18 AND EXTRACT(HOUR FROM jammasuk) <=18) AS ja18,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 19 AND EXTRACT(HOUR FROM jammasuk) <=19) AS ja19,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 20 AND EXTRACT(HOUR FROM jammasuk) <=20) AS ja20,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 21 AND EXTRACT(HOUR FROM jammasuk) <=21) AS ja21,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 22 AND EXTRACT(HOUR FROM jammasuk) <=22) AS ja22,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 23 AND EXTRACT(HOUR FROM jammasuk) <=23) AS ja23
		FROM COBAKELUAR
		");
		return $q2->result();
	}
	public function stat3()
	{
		$q3=$this->db->query("SELECT DISTINCT
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 0 AND EXTRACT(HOUR FROM jammasuk) <=0) AS j0,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 0) AS ja0,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 1 AND EXTRACT(HOUR FROM jammasuk) <=1) AS j1,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 1) AS ja1,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 2 AND EXTRACT(HOUR FROM jammasuk) <=2) AS j2,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 2) AS ja2,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 3 AND EXTRACT(HOUR FROM jammasuk) <=3) AS j3,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 3) AS ja3,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 4 AND EXTRACT(HOUR FROM jammasuk) <=4) AS j4,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 4) AS ja4,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 5 AND EXTRACT(HOUR FROM jammasuk) <=5) AS j5,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 5) AS ja5,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 6 AND EXTRACT(HOUR FROM jammasuk) <=6) AS j6,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 6) AS ja6,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 7 AND EXTRACT(HOUR FROM jammasuk) <=7) AS j7,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 7) AS ja7,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 8 AND EXTRACT(HOUR FROM jammasuk) <=8) AS j8,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 8) AS ja8,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 9 AND EXTRACT(HOUR FROM jammasuk) <=9) AS j9,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 9) AS ja9,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 10 AND EXTRACT(HOUR FROM jammasuk) <=10) AS j10,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 10) AS ja10,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 11 AND EXTRACT(HOUR FROM jammasuk) <=11) AS j11,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 11) AS ja11,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 12 AND EXTRACT(HOUR FROM jammasuk) <=12) AS j12,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 12) AS ja12,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 13 AND EXTRACT(HOUR FROM jammasuk) <=13) AS j13,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 13) AS ja13,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 14 AND EXTRACT(HOUR FROM jammasuk) <=14) AS j14,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 14) AS ja14,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 15 AND EXTRACT(HOUR FROM jammasuk) <=15) AS j15,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 15) AS ja15,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 16 AND EXTRACT(HOUR FROM jammasuk) <=16) AS j16,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 16) AS ja16,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 17 AND EXTRACT(HOUR FROM jammasuk) <=17) AS j17,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 17) AS ja17,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 18 AND EXTRACT(HOUR FROM jammasuk) <=18) AS j18,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 18) AS ja18,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 19 AND EXTRACT(HOUR FROM jammasuk) <=19) AS j19,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 19) AS ja19,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 20 AND EXTRACT(HOUR FROM jammasuk) <=20) AS j20,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 20) AS ja20,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 21 AND EXTRACT(HOUR FROM jammasuk) <=21) AS j21,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 21) AS ja21,
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 22 AND EXTRACT(HOUR FROM jammasuk) <=22) AS j22,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 22) AS ja22,	
		(SELECT COUNT(*) FROM cobakeluar WHERE EXTRACT(HOUR FROM jam) >= 23 AND EXTRACT(HOUR FROM jammasuk) <=23) AS j23,(SELECT COUNT(*) FROM coba WHERE EXTRACT(HOUR FROM jam) <= 23) AS ja23
		FROM COBAKELUAR
		");
		return $q3->result();
	}
}
?>